name: Bug Report
description: Use this template to report a bug.
title: "[BUG] "
labels: ["bug"]
assignees:
  - ""  # Assign to no one by default; this can be an array of usernames or a single username

body:
  - type: checkboxes
    id: bug_type
    attributes:
      label: "Please choose the type of bug:"
      options:
        - label: "UI Issue"
        - label: "Performance Issue"
        - label: "Crash"
        - label: "Other"
    required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Provide a detailed description of the issue."
      placeholder: "Describe the bug here..."
    required: true
      
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the problem."
      placeholder: "1. \n2. \n3."
    required: true
      
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "What did you expect to happen?"
    required: true
