name: Website Issues
description: Report issues with websites that happen when using a filterlist.
labels: ["issue"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help fix issues that occur when using a filterlist. 
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I click here this happens
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to page X
        2. Click here
        3. Click there
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
